### ISSUE TITLE
Docker images should be removed after action execution

### ISSUE THREAD

**Issue by mquinzin** [mini-bomba/create-github-release#1]
Hi, first of all, I really appreciate your action it is very useful.
But for each run, a new image (called 4c0175) with a diferent tag, is created.
Why don't you consider removing this image at the end of the execution ?
Running it 10 times = 10x238MB = 2.4GB !!!
Thx.

**Comment by mini-bomba** [comment]
Hi, thanks for reporting!
I assume you're using selfhosted runners, since this isn't much of an issue on github-hosted ones.
While docker might show you that the image takes up 238MB, docker should reuse some of the layers. The image I'm basing on weighs around 120MB, so in the worst case scenario each image version may take up to 120MB.
Though I think it might be your runners' responsibility to clean up or cache built containers, I've still found a workaround.

I'm working right now on publishing built docker images on ghcr.io to allow your runners to download & reuse prebuilt images.
I'm also reordering commands in the Dockerfile to allow for more layer reuse, fixing some bugs that came up with this new feature and adding the `--no-install-recommends` flag to apt (it saves 8MBs in my testing - a little over 3% of the image size & it doesn't seem to be causing issues)
I'll add instructions on how to use this new workaround in the readme when I finish the feature.

**Comment by mini-bomba** [comment]
Hi, I've just pushed some changes which may fix your issue.
Here's a link to the new content in the README file explaining how to use prebuilt images: https://github.com/mini-bomba/create-github-release#using-the-ghcrio-image-instead-of-building-on-demand

**Comment by mquinzin** [comment]
Great new, many thx, I'm going to test this soon !

**Comment by mquinzin** [comment]
Hi it seems that the correct line in workflow is
uses: mini-bomba/create-github-release:v1.1.0 (instead of @).
Other question, did you change your script behaviour ?
It complains when tag already exist, whereas it was not complaining before ... was useful to upgrade assets in an existing release/tag ...
Thx
The best behaviour (for me) would be to create the release/tag couple if it does not exist, and to use already existing if it already exist ..

**Comment by mquinzin** [comment]
I opene another issue for the behaviour ;-p
